"""add is_active to categories suppliers units

Revision ID: 72783de39fbc
Revises: 501e77e7d5db
Create Date: 2026-07-11 16:50:32.313161

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '72783de39fbc'
down_revision: Union[str, Sequence[str], None] = '501e77e7d5db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('categories', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('suppliers', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.add_column('units', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('units', 'is_active')
    op.drop_column('suppliers', 'is_active')
    op.drop_column('categories', 'is_active')
    # ### end Alembic commands ###
